"""
Fichier de configuration GitHub Actions pour l'entraînement, l'évaluation et la génération de documentation.
"""

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Preprocess data
        run: python script/preprocessing.py

      - name: Train models
        run: python script/train.py

      - name: Evaluate models
        run: python script/evaluation.py

      - name: Generate documentation
        run: |
          ./run_pydoc.sh

      - name: Archive and Upload Model and Doc
        run: zip -r output.zip model doc

      - name: Send Email with Model and Documentation
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python script/send_email.py