name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Git LFS
        run: git lfs install

      - name: Pull LFS files
        run: git lfs pull

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Preprocess data
        run: python Scripts/preprocessing.py

      - name: Train models
        run: python Scripts/training.py

      - name: Evaluate models
        run: python Scripts/evaluation.py

      - name: Generate documentation
        run: |
          ./run_doc.sh

      - name: Archive and Upload Model and Doc
        run: zip -r output.zip model doc

      - name: Send Email with Model and Documentation
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python script/send_email.py
