name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Git LFS
        run: |
          git lfs install
          git lfs fetch --all
          git lfs checkout
          git lfs pull

      - name: Verify LFS Checkout
        run: |
          echo "Listing data directory:"
          ls -lh data/
          echo "First 10 lines of diabetes.csv:"
          head -n 10 data/diabetes.csv

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Preprocess data
        run: python Scripts/preprocessing.py

      - name: Train models
        run: python Scripts/training.py

      - name: Evaluate models
        run: python Scripts/evaluation.py

      - name: Read evaluation scores and make decision
        id: evaluate
        run: |
          score=$(jq -r '.svm' model/scores.json)
          echo "Score du modèle SVM: $score"
          if (( $(echo "$score > 0.80" | bc -l) )); then
            echo "deploy=true" >> $GITHUB_ENV
          else
            echo "deploy=false" >> $GITHUB_ENV
          fi

      - name: Deploy model (conditioned)
        if: ${{ env.deploy }} == 'true'
        run: echo "Déploiement du modèle sélectionné"

      - name: Rendre le script exécutable
        run: chmod +x run_doc.sh

      - name: Generate documentation
        run: ./run_doc.sh

      - name: Archive and Upload Model and Doc
        run: zip -r output.zip model Docs

      - name: Send Email with Model and Documentation
        run: python Scripts/send_email.py
